name: BuildImage
run-name: "Build Image run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    workflow_call:
    workflow_dispatch:
concurrency:
    group: build-image ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    build-image-android:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'
            - name: Clean Android build
              env:
                ANDROID_DIR: ${{ github.workspace }}/android
              run: python scripts/clean_android_build.py
            - name: Remove duplicate PackageList.java files
              env:
                ANDROID_DIR: ${{ github.workspace }}/android
              run: |
                duplicates=$(python scripts/find_duplicate_package_list_classes.py | grep -v "No duplicate")
                if [ ! -z "$duplicates" ]; then
                  echo "$duplicates" | while read -r file; do
                    rm "$file"
                    echo "Removed duplicate file: $file"
                  done
                fi
            - name: Regenerate autolinking files
              run: |
                cd android
                ./gradlew generateAutolinkingPackageList
            - name: Clear Metro cache
              run: npx react-native start --reset-cache
            - name: Build Android APK
              run: |
                cd android
                ./gradlew assembleRelease --info
            - name: Upload Android APK
              uses: actions/upload-artifact@v3
              with:
                  name: app-release.apk
                  path: android/app/build/outputs/apk/release/app-release.apk
    build-image-ios:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Build iOS IPA
              run: |
                cd ios
                xcodebuild -workspace GreetingHexJavascriptReact.xcworkspace -scheme GreetingHexJavascriptReact -configuration Release -archivePath GreetingHexJavascriptReact.xarchive archive
                xcodebuild -exportArchive -archivePath GreetingHexJavascriptReact.xarchive -exportOptionsPlist exportOptions.plist -exportPath .
            - name: Upload iOS IPA
              uses: actions/upload-artifact@v3
              with:
                  name: GreetingHexJavascriptReact.ipa
                  path: ios/GreetingHexJavascriptReact.ipa