name: CD
run-name: 'CD run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: cd ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
