name: CI
run-name: 'CI run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  push:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ci ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-image:
    permissions:
      contents: read
      packages: read
    secrets: inherit
    uses: ./.github/workflows/build-image.yml
