name: Device Tests
run-name: 'Device Tests run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  push:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: device-test ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  application:
    permissions:
      contents: read
    secrets: inherit
    uses: ./.github/workflows/application.yml
  network:
    permissions:
      contents: read
    secrets: inherit
    uses: ./.github/workflows/network.yml
