name: Network Tests
run-name: 'Network Tests run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: network-test ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  no-network:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Step not implemented yet
        continue-on-error: true
        run: |
          echo "This job is not yet implemented"
          exit 1
  good-network:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Step not implemented yet
        continue-on-error: true
        run: |
          echo "This job is not yet implemented"
          exit 1
  bad-network:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Step not implemented yet
        continue-on-error: true
        run: |
          echo "This job is not yet implemented"
          exit 1
