name: Non-Device Tests
run-name: 'Non-Device Tests run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  push:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: non-device-test ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  functional:
    uses: ./.github/workflows/functional.yml
  security:
    uses: ./.github/workflows/security.yml
  performance:
    permissions:
      contents: read
    secrets: inherit
    uses: ./.github/workflows/performance.yml
  accessibility:
    uses: ./.github/workflows/accessibility.yml
  data:
    uses: ./.github/workflows/data.yml
  production:
    uses: ./.github/workflows/production.yml
  cross-functional-requirements:
    uses: ./.github/workflows/cross-functional-requirements.yml
  visual:
    uses: ./.github/workflows/visual.yml
