name: Performance Tests
run-name: 'Performance Tests run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: performance-test ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  job-not-implemented-yet:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Step not implemented yet
        continue-on-error: true
        run: |
          echo "This job is not yet implemented"
          exit 1
