name: Visual Tests
run-name: 'Visual Tests run by @${{ github.actor }}, event: ${{ github.event_name }}'
on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: visual-test ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  job-not-implemented-yet:
    runs-on: ubuntu-latest
    steps:
      - name: Step not implemented yet
        run: |
          echo "Not implemented yet"
